blog/urls.py
from django.urls import path
from . import views 
#from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns=[
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tags/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('create/', views.postCreate, name='create_post'),
    path('edit/<int:post_id>/', views.postEdit, name='edit_post'),
    path('my-articles/', views.InstructorPosts, name='instructor_posts'),
    path('delete/<int:post_id>/', views.postDelete, name='delete_post'),
    #path('feed/', LatestPostFeed(), name="post_feed"),
    path('search/', views.post_search, name='post_search'),
]

students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'students'

urlpatterns = [
    path('register/', views.StudentRegistrationView.as_view(), name='student_registration'),
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path('courses/<pk>/',cache_page(60*15) (views.StudentCourseDetailView.as_view()), name='student_course_detail'),
    path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    path('course/<pk>/<module_id>/', cache_page(60*15) (views.StudentCourseDetailView.as_view()), name='student_course_detail_module'),
]

blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode
from ckeditor_uploader.fields import RichTextUploadingField

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextUploadingField(blank=True)
    image = models.ImageField(upload_to="images", blank=True)
    publish = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(unidecode(self.title))
        super(Post, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, 
                                            self.publish.month, 
                                            self.publish.day, 
                                            self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.owner} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment, Post

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body':forms.Textarea(attrs={'cols':100, 'rows':80}),
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'body', 'tags' ,'status')

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import EmailPostForm, CommentForm, PostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

def post_list(request, tag_slug=None):    
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    
    paginator =Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', { 'page':page, 'posts':posts, 'tag':tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    status='published', 
                                    publish__year=year, 
                                    publish__month=month, 
                                    publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.owner = request.user
                new_comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similiar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similiar_posts = similiar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html',{'post':post, 'comments':comments, 
                        'new_comment': new_comment, 'comment_form': comment_form,
                        'similiar_posts':similiar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you to read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n " \
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'mehedi.hassan202111@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{'post':post, 'form':form, 'sent':sent})

def postCreate(request):
    new_post = None
    if request.user.groups.filter(name='Instructors'):
        if request.method == 'POST':
            form = PostForm(data=request.POST)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.author = request.user
                new_post.save()
            return HttpResponseRedirect(new_post.get_absolute_url())
        else:
            form = PostForm()
    else:
        return HttpResponseRedirect(reverse('blog:post_list'))
    return render(request, 'blog/post/create_post.html', {'form':form})

def postEdit(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(instance=post, data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
            return HttpResponseRedirect(post.get_absolute_url())
        else:
            form = PostForm(instance=post)
    else:
        return HttpResponseRedirect(reverse('blog:post_list'))
    return render(request, 'blog/post/edit_post.html', {'form':form, 'post':post })
        
def InstructorPosts(request):
    if request.user.groups.filter(name='Instructors'):
        user = request.user
        all_posts = Post.objects.filter(author=user)
        return render(request, 'blog/post/instructor_posts.html', {'all_posts':all_posts})
    else:
        return HttpResponseRedirect('/articles')

def postDelete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        if request.method == 'POST':
            post.delete()
            return HttpResponseRedirect('/articles/my-articles')
        return render(request, 'blog/post/delete_post.html', {'post':post})
    return HttpResponseRedirect('/articles')

def post_search(request):
    query = request.GET.get('search')
    results = []
    
    if query:
        search_vector = SearchVector('title', 'body')
        search_query = SearchQuery(query)
        results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'query':query, 'results':results})

blog/templates/blog/post/create_post.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="container">
    <h1>Create a new post</h1>

    <div class="row">
        <form method="POST">
            <div class="col-sm-auto">
                <div class="form-group">
                {{ form.as_p}}
                {{ form.media }}
                {% csrf_token %}
                <input type="submit" value="save post">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/post/delete_post.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
<div class="card col-lg-auto">
    <div class="card-header">
    {{post.title}}
</div>
   <p>{{post.body|markdown|truncatewords_html:30}}</p>
   </div>
   <div class="card">
    <div class="card-body">
    <form method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col">
                    Are you sure you want to delete this item?
                </div>
            </div>
    <div class="input-group mb-2">
        <input type="submit" role="button" aria-label="Default" style="background-color: red;" value="yes">
    </div>
        <p><a href="{% url 'blog:instructor_posts' %}" class="btn btn-secondary" role="button">No</a></p>
    </form>
</div>
</div>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load blog_tags %}
{% load static %}


{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div id="main-content" class="blog-page">
        <div class="container">
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 left-box">
                    <div class="card single_post">
                        <div class="body">
                            <div class="img-post">
                                <img class="d-block img-fluid" src="{% if post.image %}{{ post.image.url }}{% else %} {% static 'img/no_img.png' %}{% endif %}" alt="First slide">
                                <p class="tags">
                                    Tags:
                                    {% for tag in post.tags.all %}
                                    <a style="color:rgb(148, 180, 101)" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                        {{ tag.name }}
                                    </a>
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </p>
                            </div>
                            {% if request.user == post.author %}
                            <p class="date">
                                <a href="{% url 'blog:edit_post' post.id %}">Edit post</a>&nbsp;&nbsp;  
                                <a href="{% url 'blog:delete_post' post.id %}">Delete post</a>&nbsp;&nbsp;
                            {% endif %}
                                <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
                            </p>
                            <br>
                            <h3><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
                            <p class="date">
                                Published {{ post.publish }} by {{ post.author }}
                            </p>
                            <p>{{ post.body|markdown }}</p>
                        </div>                        
                    </div>
                    <div class="card">
                            <div class="header">
                                <h2>Comments {{ post|total_comments}}</h2>
                            </div>
                            <div class="body">
                                <ul class="comment-reply list-unstyled">
                                    {% for comment in comments %}
                                    <li class="row clearfix">
                                        <div class="icon-box col-md-2 col-4"><img class="img-fluid img-thumbnail" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Awesome Image"></div>
                                        <div class="text-box col-md-10 col-8 p-l-0 p-r0">
                                            <h5 class="m-b-0">{{ comment.owner.get_full_name }} </h5>
                                            <p> {{ comment.body }}</p>
                                            <ul class="list-inline">
                                                <li><a href="javascript:void(0);">{{ comment.created }}</a></li>
                                            </ul>
                                        </div>
                                    </li>
                                    {% empty %}
                                    <p>There are no comments yet.</p>
                                    {% endfor %}
                                </ul>                                        
                            </div>
                        </div>
                        <div class="card">
                            <div class="header">
                                {% if new_comment %}
                                <div class="alert alert-success" role="alert">
                                    <h2>Your comment has been added.</h2>
                                </div>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                <h3>Leave a reply <small>Required fields are marked*</small></h3>
                            </div>
                            
                            <div class="body">
                                <div class="comment-form">
                                    <form method="POST" class="row clearfix">
                                        <div class="col-lg-auto">
                                            <div class="row">
                                            <div class="form-group">
                                                {% csrf_token %}
                                                {{ comment_form.body|as_crispy_field }}
                                            </div>
                                        </div>
                                            <button type="submit" class="btn btn-block btn-primary">SUBMIT</button>
                                        </div>                                
                                    </form>
                                </div>
                                {% else %}
                            <h4><a href="{% url 'login' %}">Log in</a> to leave a reply 
                                <small>Don't have an account yet? </small><a href="{% url 'students:student_registration' %}">Sign Up</a></h4>
                            {% endif %}
                            </div>
                        </div>
                </div>
                <div class="col-lg-4 col-md-12 right-box">
                    <div class="card">
                        <div class="body search">
                            <div class="input-group m-b-0">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-search"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Search...">                                    
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="header">
                            <h2>Categories Clouds</h2>
                        </div>
                        <div class="body widget">
                            <ul class="list-unstyled categories-clouds m-b-0">
                                {% all_tags as total_tags %}
                                {% for tag in total_tags %}
                                <li><a href="javascript:void(0);">{{ tag }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="card">
                        <div class="header">
                            <h2>Recommended Posts</h2>
                        </div>
                        <div class="body widget popular-post">
                            <div class="row">
                                <div class="col-lg-12">
                                    {% for post in similiar_posts %}
                                    <div class="single_post">
                                        <p class="m-b-0"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                                        <span>{{post.publish}}</span>
                                        <div class="img-post">
                                            <a href="{{ post.get_absolute_url }}"><img src="{% if post.image %}{{ post.image.url }}{% else %} {% static 'img/no_img.png' %}{% endif %}" alt="Awesome Image" width="400" height="150"></a>                                       
                                        </div>                                            
                                    </div>
                                    {%  endfor %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="header">
                            <h2>Popular Posts</h2>                        
                        </div>
                        <div class="body widget popular-post">
                            <div class="row">
                                <div class="col-lg-12">
                                    {% get_most_commented_posts as most_commented_posts %}
                                    {% for post in most_commented_posts %}
                                    <div class="single_post">
                                        <p class="m-b-0"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                                        <span>{{post.publish}}</span>
                                        <div class="img-post">
                                            <img src="{% if post.image %}{{ post.image.url }}{% else %} {% static 'img/no_img.png' %}{% endif %}" alt="Awesome Image">                                        
                                        </div>                                            
                                    </div>
                                    {%  endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

blog/templates/blog/post/edit_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit Post{% endblock %}

{% block content %}
<div class="container-fluid col-lg-8" style="text-align: justify; margin: 2rem;">
    <h3>Edit Your Post</h3>
    <form method="POST" enctype="multipart/form-data">
    <div class="form-group">
        {{form.media}}
        {{form|crispy}}
        {% csrf_token %}
        <input type="submit" value="save post">
    </div>
</form>
</div>

{% endblock %}

blog/templates/blog/post/instructor_posts.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block title %}My Articles{% endblock %}

{% block content %}
<div id="sidebar">
    <p style="text-align: center; padding-top: 10px;"><a href="{% url "blog:create_post" %}" class="button">Write new article</a></p>
</div>
<div class="container col-lg-10">
    <div class="breadcrumb">
    <h2>My Articles</h2>
</div>
    {% for post in all_posts %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
            <a style="color:rgb(148, 180, 101)" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    </h4>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
</div>

{% endblock %}

blog/templates/blog/post/latest_posts.html
{% load static %}
{% for post in latest_posts %}
<div class="single_post">
    <p class="m-b-0"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    <span>{{post.publish}}</span>
    <div class="img-post">
        <img src="{% if post.image %}{{ post.image.url }}{% else %} {% static 'img/no_img.png' %}{% endif %}" alt="Awesome Image">                                        
    </div>                                            
</div>
{%  endfor %}

blog/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock %}


{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />

<section>
<div class="container">
    <div class="text-center mb-5">
        <h5 class="text-primary h6">Geekacademy</h5>
        <h2 class="display-20 display-md-18 display-lg-16">
            {% if tag %}
                <h3>Posts tagged with "{{ tag.name }}"</h3>
            {% else %}
            Most recent Tutorials</h2>
            {% endif %}
    </div>
    <div class="row">
        {% for post in posts %}
        <div class="col-lg-4 col-md-6 mb-2-6">
            <article class="card card-style2">
                <div class="card-img">
                    <img class="rounded-top" src="{% if post.image %}{{ post.image.url }}{% else %} {% static 'img/no_img.png' %}{% endif %}" alt="..." height="280">
                    <div class="date"><span>{{post.publish.day}}</span>{{post.publish.month|month_name}}</div>
                </div>
                <div class="card-body">
                    <h3 class="h5"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <p class="display-30">{{ post.body|markdown|truncatewords_html:20 }}</p>
                    <a href="{{ post.get_absolute_url }}" class="read-more">read more</a>
                </div>
                <div class="card-footer">
                    <ul>
                        <li><a href="{{ post.get_absolute_url }}"><i class="fas fa-user"></i>{{ post.author }}</a></li>&nbsp;&nbsp;
                        <li><a href="{{ post.get_absolute_url }}"><i class="far fa-comment-dots"></i><span>{{ post|total_comments}}</span></a></li>
                    </ul>
                </div>
            </article>
        </div>
        {% endfor %}
    </div>
    {% include 'pagination.html' with page=posts %}
</div>
</section>
{% endblock %}

blog/templates/blog/post/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<div class="main-content" id="content">
<h1>Posts containing "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
Found {{ total_results }} result{{ total_results|pluralize }}
{% endwith %}
</h3>
{% for post in results %}
<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
{{ post.body|markdown|truncatewords_html:15 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
{% endif %}
</div>

{% endblock %}

blog/templates/blog/post/share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Share a Post{% endblock %}

{% block content %}
<div class="container">
    {% if sent %}
        <h1>E-mail was successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to}}</p>
    {% else %}
    <h2>Share "What is a Reverse Proxy vs. Load Balancer?" by e-mail</h2>
    <div class="row">
        <form method="POST">
            <div class="col-sm-12">
                <div class="form-group">
                {{ form|crispy }}
                {% csrf_token %}
                <input type="submit" value="Send E-mail">
                </div>
            </div>
        </form>
    </div>
</div>
    {% endif %}
{% endblock %}  